#!/bin/sh

# Selects either `doas` or `sudo`
[[ -e /usr/bin/doas && -e /etc/doas.conf ]] && { SUPERU="doas" && alias sudo="doas" } || SUPERU="sudo"

# ===GENERAL===

	alias ls="ls --color=auto"
	alias update-grub="$SUPERU grub-mkconfig -o /boot/grub/grub.cfg"
	alias gut="git"
	alias tlmgr="tllocalmgr"
	alias spacenavcfg="spnavcfg"


# ===PACMAN===

	alias ps="pacman -Ss"
	alias pi="$SUPERU pacman -S"
	alias pu="$SUPERU pacman -Syy"
	alias pupgrade="$SUPERU pacman -Syyu"
	alias pr="$SUPERU pacman -Rsn"


# ===YAY===

	alias ys="yay -Ss"
	alias yi="yay -S"
	alias yu="yay -Syy"
	alias yupgrade="yay -Syyu"
	alias yr="yay -Rsn"


# ===XBPS===

	alias xs="xbps-query -Rs"
	alias xi="$SUPERU xbps-install -Sy"
	alias xu="$SUPERU xbps-install -S"
	alias xupgrade="$SUPERU xbps-install -Su"


# ===YOUTUBE-DL===

	alias yt="youtube-dl"
	alias yt-archive="youtube-dl --download-archive"


# ===POWER OPTIONS===

	alias poweroff="$SUPERU poweroff"
	alias shutdown="$SUPERU poweroff"

	alias reboot="$SUPERU reboot"
	alias suspend="$SUPERU systemctl suspend"
