#!/bin/sh

# ===FreeBSD===
#
#	# Get capacitya and status from apm
#	capacity=$( apm | sed -n 5p | sed "s/Remaining battery life: //;s/%//" ) || exit
#	status=$( apm | sed -n 6p | sed "s/Remaining battery time: //" )
#
#	# Warn at 15%
#	[ "$status" = "Discharging" ] && [ "$capacity" -le 15 ] && warn="❗"
#
#	printf "%s%s%s\n" "$(echo "$status" | sed "s/unknown/⚡/;s/[0-9]:[0-9][0-9]:[0-9][0-9]/🔋/;s/ 0*/ /g;s/ :/ /g")" "$warn" "$(echo "$capacity" | sed -e 's/$/%/')"
#	unset warn
		

# ===GNU/Linux===

	for battery in /sys/class/power_supply/BAT?
	do

		# Gets % left and whether charging or nought
		capacity=$(cat "$battery"/capacity) || exit
		status=$(cat "$battery"/status)

		# Warn at 15%
		[ "$status" = "Discharging" ] && [ "$capacity" -le 15 ] && warn="❗"

		# Luke's sed script
		printf "%s%s%s\n" "$(echo "$status" | sed "s/,//;s/Discharging/🔋/;s/Not charging/🛇/;s/Charging/⚡/;s/Unknown/❓/;s/Full/🔌/;s/ 0*/ /g;s/ :/ /g")" "$warn" "$(echo "$capacity" | sed -e 's/$/%/')"
		unset warn

	done
