#!/bin/sh

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"
shebang=$(sed -n 1p "$file")

cd "$dir" || exit

textype() { \
	command="pdflatex"
	( sed 5q "$file" | grep -i -q 'xelatex' ) && command="xelatex"
	$command --output-directory="$dir" "$base" &&
	grep -i addbibresource "$file" >/dev/null &&
	biber --input-directory "$dir" "$base" &&
	$command --output-directory="$dir" "$base" &&
	$command --output-directory="$dir" "$base"
}
	

shebangtest() {
	case "$shebang" in
		\#\!*) "$file" ;;
		*) sent "$file" 2>/dev/null & ;;
	esac
}

case "$file" in
	*\.tex) textype "$file" ;;
	*\.md) pandoc -t html5 --css $HOME/.bin/tools/pandoc2pdf.css "$file" -o "$base".html && wkhtmltopdf -s Letter "$base".html "$base".pdf ;;
	*\.ms) groff -k -ms "$file" -T pdf > "$base".pdf ;;
	*\.fountain) node $HOME/Downloads/.src/afterwriting-labs/awc.js --source "$file" --pdf "$base".pdf --config $HOME/Downloads/.src/afterwriting-labs/config.json --overwrite ;;
	*\.ftn) node $HOME/Downloads/.src/afterwriting-labs/awc.js --source "$file" --pdf "$base".pdf --config $HOME/Downloads/.src/afterwriting-labs/config.json --overwrite ;;
	*\.c) gcc "$file" -o "$base" ;;
	*\.C) gcc "$file" -o "$base" ;;
	*\.go) go build "$file" ;;
	*) shebangtest ;;
esac
