#!/bin/bash

#======================================================================#
# ===MONITOR FIX===                                                    #
#======================================================================#

	xrandr --output   DisplayPort-0 \
		    -r 60                   \
		   --primary                \
		   --left-of  HDMI-A-0      ;

	xrandr --output   HDMI-A-0      \
		    -r 60                   \
	       --right-of DisplayPort-0 ;


#======================================================================#
# ===KEYBOARDS & MICE===                                               #
#======================================================================#

	#------------------------------------------------------------------#
	# Custom Dvorak layouts                                            #
	#------------------------------------------------------------------#

###		setxkbmap   \
###			-layout lingdvorak,lingdvorak,lingdvorak    \
###			-variant ,alt,arun                          \
###			-option 'grp:alt_caps_toggle',              \
###					'lv3:ralt_switch',                  \
###					'caps:escape_shifted_capslock' ;

###		setxkbmap   \
###			-layout lingdvorak,lingdvorak      \
###			-variant ,alt                      \
###			-option 'grp:alt_shift_toggle',    \
###					'lv3:ralt_switch',         \
###					'caps:escape_shifted_capslock' ;

###		setxkbmap	\
###			-layout lingdvorak,lingdvorak      \
###			-variant us,arunus                 \
###			-option 'grp:alt_shift_toggle',    \
###					'lv3:ralt_switch',         \
###					'caps:escape_shifted_capslock' ;

		setxkbmap	\
			-layout lingdvorak,lingdvorak      \
			-variant us,altus                  \
			-option 'grp:alt_shift_toggle',    \
					'lv3:ralt_switch',         \
					'caps:escape_shifted_capslock' ;


	#------------------------------------------------------------------#
	# Natural Scrolling                                                #
	#                                                                  #
	# TODO: Find a system-wide option.                                 #
	#------------------------------------------------------------------#

		xinput set-prop                 \
			"Nordic 2.4G Wireless Receiver Mouse"   \
			"libinput Natural Scrolling Enabled"    \
			1                                       ;


#======================================================================#
# ===LESSKEY===                                                        #
#======================================================================#

###	#------------------------------------------------------------------#
###	# `lesskey` sets the keybindintgs for `less`                       #
###	#------------------------------------------------------------------#
###
###		lesskey $HOME/.config/less/lessrc


#======================================================================#
# ===WINDOW MANAGER===                                                 #
#======================================================================#

	#------------------------------------------------------------------#
	# ===WM===                                                         #
	#------------------------------------------------------------------#

		xscreensaver --no-splash &

	#------------------------------------------------------------------#
	# ===WINDOW TRANSPARCENCY===                                       #
	#------------------------------------------------------------------#

		/usr/local/bin/picom --dbus -b &

	#------------------------------------------------------------------#
	# ===KAKOUNE===                                                    #
	#------------------------------------------------------------------#

		/usr/bin/kak -s 1 -d &

	#------------------------------------------------------------------#
	# ===PIPEWIRE===                                                   #
	#------------------------------------------------------------------#

		pipewire &

		pipewire-pulse &

	#------------------------------------------------------------------#
	# ===AUTOMOUNTING===                                               #
	#------------------------------------------------------------------#

		udiskie &

	#------------------------------------------------------------------#
	# ===WM===                                                         #
	#------------------------------------------------------------------#

		# Desktop background (WM Agnostic)
		# TODO: Find cross-device solution, i.e. many paths
		while feh --bg-fill --randomize --no-fehbg $HOME/Pictures/Wallpapers/*
		do
			sleep 900    # Sleep 15min (900 sec's)
		done &

		# DWM Status Bar
		while xsetroot -name "[$( cpu_temp ) | $( date "+🌎%m-%d-%y" ) | $( date "+🕓%l:%M%p" )]"
		do
			sleep 5
		done &

		# DWM start
		dbus-run-session dwm
