#!/bin/sh
#
# ===Monitor Fix===

	#xrandr --output DVI-D-0 --left-of HDMI-A-0 ;
	#xrandr --output DVI-D-1 --right-of HDMI-A-0 ;

	xrandr --output DVI-D-1  --left-of HDMI-1 ;
	xrandr --output DVI-D-2 --right-of HDMI-1 ;


# ===WM STATUS BAR===

	while xsetroot -name "[$( net_check ) | $( cpu_temp ) | $( date "+🌎%m-%d-%y" ) | $( date "+🕓%I:%M%p" )]"; do
		sleep 5
	done &


# ===WM BACKGROUND===

	while feh --bg-fill --randomize ~/Pictures/Wallpapers/*.jpg; do
		sleep 900							# Sleep 15min (900 sec's)
	done &


# ===WINDOW TRANSPARCENCY===

	picom &


# ===KEYBOARD===

	# Custom Dvorak layouts
	setxkbmap \
		-layout lingdvorak,lingdvorak,lingdvorak \
		-variant ,alt,arun \
		-option 'grp:alt_caps_toggle','lv3:ralt_switch' &


# ===WM===

	exec dwm
