#!/bin/sh
#
# ===Monitor Fix===

	#xrandr --output DVI-D-0 --left-of HDMI-A-0 ;
	#xrandr --output DVI-D-1 --right-of HDMI-A-0 ;

	xrandr --output DVI-D-1  --left-of HDMI-1 ;
	xrandr --output DVI-D-2 --right-of HDMI-1 ;


# ===KEYBOARDS & MICE===

	# Custom Dvorak layouts
	setxkbmap \
		-layout lingdvorak,lingdvorak \
		-variant ,alt \
		-option 'grp:alt_caps_toggle','lv3:ralt_switch' ;


	# Natural Scrolling
	# To find this, you type `xinput list` and then find your mouse.
	# Then, type `xinput list-props <mouse-id>`
	# Find your natural scrolling option; the anatomy is:
	# xinput set-prop <mouse-id> <nat-scroll-id> <0 for off; 1 for high>
#	xinput set-prop 11 276 1 ;


while true; do

	# ===WM STATUS BAR===

		while xsetroot -name "[$( net_check ) | $( cpu_temp ) | $( date "+🌎%m-%d-%y" ) | $( date "+🕓%I:%M%p" )]"; do
			sleep 5
		done &


	# ===WM BACKGROUND===

		while feh --bg-fill --randomize ~/Pictures/Wallpapers/*.jpg; do
			sleep 900							# Sleep 15min (900 sec's)
		done &


	# ===WINDOW TRANSPARCENCY===

		picom &


	# ===WM===

		dbus-launch --exit-with-session dwm &&


	# ===BLUEMAN===

		blueman-applet

done
